import commandLineArgs from 'command-line-args';
import getUsage from 'command-line-usage';

const optionList = [
    {
        name: 'bundle',
        type: String,
        defaultOption: true,
        description: 'path to the unpacked bundle file generated by `meteor build`',
    },
    {
        name: 'config',
        alias: 'c',
        type: String,
        description: 'path to the pm2 config file',
    },
    {
        name: 'settings',
        alias: 's',
        type: String,
        description: 'path to the settings file, relative to the `private` ' +
        'folder (like you would use it with `Assets.getText()`)',
    },
];

export const options = commandLineArgs(optionList);

if (!options.bundle || !options.config || !options.settings) {
    const sections = [
        {
            header: 'Usage',
            content: 'node . [bold]{--config=}path/to/pm2-config.json ' +
            '[bold]{--settings=}private/settings.json ' +
            '[italic]{[--bundle=]}path/to/bundle',
        },
        {
            header: 'Options',
            optionList,
        },
    ];
    const usage = getUsage(sections);
    console.log(usage);
    process.exit(1);
}